-- DỮ LIỆU MẪU cho trang Build PC: danh mục linh kiện + khoảng 40 linh kiện phổ biến kèm thông số tương thích.
-- Giá chỉ để THỬ NGHIỆM (tham khảo), hãy sửa giá/tồn kho/ảnh trong trang quản trị trước khi bán thật.
-- Chạy SAU khi đã nâng cấp database (npm run migrate-db -- --apply). Chạy lại không tạo trùng (bỏ qua sản phẩm cùng tên).
-- MySQL Workbench / DBeaver: mở file, chọn schema shopdb rồi chạy cả file.

SET NAMES utf8mb4;

-- 1. Danh mục linh kiện (type = component)
INSERT INTO `categories` (`name`, `type`) SELECT 'CPU - Bộ vi xử lý', 'component' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `categories` WHERE `name` = 'CPU - Bộ vi xử lý');
INSERT INTO `categories` (`name`, `type`) SELECT 'Mainboard - Bo mạch chủ', 'component' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `categories` WHERE `name` = 'Mainboard - Bo mạch chủ');
INSERT INTO `categories` (`name`, `type`) SELECT 'RAM', 'component' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `categories` WHERE `name` = 'RAM');
INSERT INTO `categories` (`name`, `type`) SELECT 'Card đồ họa (VGA)', 'component' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `categories` WHERE `name` = 'Card đồ họa (VGA)');
INSERT INTO `categories` (`name`, `type`) SELECT 'Ổ cứng SSD', 'component' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `categories` WHERE `name` = 'Ổ cứng SSD');
INSERT INTO `categories` (`name`, `type`) SELECT 'Nguồn máy tính (PSU)', 'component' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `categories` WHERE `name` = 'Nguồn máy tính (PSU)');
INSERT INTO `categories` (`name`, `type`) SELECT 'Vỏ máy (Case)', 'component' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `categories` WHERE `name` = 'Vỏ máy (Case)');
INSERT INTO `categories` (`name`, `type`) SELECT 'Tản nhiệt CPU', 'component' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `categories` WHERE `name` = 'Tản nhiệt CPU');

-- 2. Linh kiện
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Intel Core i3-12100F', 'Linh kiện mẫu cho Build PC (CPU - Bộ vi xử lý).', 1900000, 10, c.id, NULL, '{"Socket": "LGA1700", "Nhân/Luồng": "4/8", "Xung tối đa": "4.3GHz", "Đồ họa tích hợp": "Không"}', 'cpu', '{"socket": "LGA1700", "tdp_w": 60, "igpu": false, "cores": 4}' FROM `categories` c WHERE c.name = 'CPU - Bộ vi xử lý' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Intel Core i3-12100F') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Intel Core i5-12400F', 'Linh kiện mẫu cho Build PC (CPU - Bộ vi xử lý).', 2700000, 10, c.id, NULL, '{"Socket": "LGA1700", "Nhân/Luồng": "6/12", "Xung tối đa": "4.4GHz", "Đồ họa tích hợp": "Không"}', 'cpu', '{"socket": "LGA1700", "tdp_w": 65, "igpu": false, "cores": 6}' FROM `categories` c WHERE c.name = 'CPU - Bộ vi xử lý' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Intel Core i5-12400F') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Intel Core i5-13400', 'Linh kiện mẫu cho Build PC (CPU - Bộ vi xử lý).', 4300000, 10, c.id, NULL, '{"Socket": "LGA1700", "Nhân/Luồng": "10/16", "Xung tối đa": "4.6GHz", "Đồ họa tích hợp": "UHD 730"}', 'cpu', '{"socket": "LGA1700", "tdp_w": 65, "igpu": true, "cores": 10}' FROM `categories` c WHERE c.name = 'CPU - Bộ vi xử lý' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Intel Core i5-13400') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Intel Core i5-14600KF', 'Linh kiện mẫu cho Build PC (CPU - Bộ vi xử lý).', 5900000, 10, c.id, NULL, '{"Socket": "LGA1700", "Nhân/Luồng": "14/20", "Xung tối đa": "5.3GHz", "Đồ họa tích hợp": "Không"}', 'cpu', '{"socket": "LGA1700", "tdp_w": 125, "igpu": false, "cores": 14}' FROM `categories` c WHERE c.name = 'CPU - Bộ vi xử lý' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Intel Core i5-14600KF') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Intel Core i7-14700K', 'Linh kiện mẫu cho Build PC (CPU - Bộ vi xử lý).', 8900000, 10, c.id, NULL, '{"Socket": "LGA1700", "Nhân/Luồng": "20/28", "Xung tối đa": "5.6GHz", "Đồ họa tích hợp": "UHD 770"}', 'cpu', '{"socket": "LGA1700", "tdp_w": 125, "igpu": true, "cores": 20}' FROM `categories` c WHERE c.name = 'CPU - Bộ vi xử lý' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Intel Core i7-14700K') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'AMD Ryzen 5 5600', 'Linh kiện mẫu cho Build PC (CPU - Bộ vi xử lý).', 2600000, 10, c.id, NULL, '{"Socket": "AM4", "Nhân/Luồng": "6/12", "Xung tối đa": "4.4GHz", "Đồ họa tích hợp": "Không"}', 'cpu', '{"socket": "AM4", "tdp_w": 65, "igpu": false, "cores": 6}' FROM `categories` c WHERE c.name = 'CPU - Bộ vi xử lý' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'AMD Ryzen 5 5600') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'AMD Ryzen 5 7500F', 'Linh kiện mẫu cho Build PC (CPU - Bộ vi xử lý).', 3300000, 10, c.id, NULL, '{"Socket": "AM5", "Nhân/Luồng": "6/12", "Xung tối đa": "5.0GHz", "Đồ họa tích hợp": "Không"}', 'cpu', '{"socket": "AM5", "tdp_w": 65, "igpu": false, "cores": 6}' FROM `categories` c WHERE c.name = 'CPU - Bộ vi xử lý' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'AMD Ryzen 5 7500F') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'AMD Ryzen 5 7600', 'Linh kiện mẫu cho Build PC (CPU - Bộ vi xử lý).', 4500000, 10, c.id, NULL, '{"Socket": "AM5", "Nhân/Luồng": "6/12", "Xung tối đa": "5.1GHz", "Đồ họa tích hợp": "Radeon"}', 'cpu', '{"socket": "AM5", "tdp_w": 65, "igpu": true, "cores": 6}' FROM `categories` c WHERE c.name = 'CPU - Bộ vi xử lý' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'AMD Ryzen 5 7600') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'AMD Ryzen 7 7800X3D', 'Linh kiện mẫu cho Build PC (CPU - Bộ vi xử lý).', 9500000, 10, c.id, NULL, '{"Socket": "AM5", "Nhân/Luồng": "8/16", "Xung tối đa": "5.0GHz", "Bộ nhớ đệm": "96MB L3 (3D V-Cache)"}', 'cpu', '{"socket": "AM5", "tdp_w": 120, "igpu": true, "cores": 8}' FROM `categories` c WHERE c.name = 'CPU - Bộ vi xử lý' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'AMD Ryzen 7 7800X3D') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'MSI PRO H610M-E DDR4', 'Linh kiện mẫu cho Build PC (Mainboard - Bo mạch chủ).', 1700000, 10, c.id, NULL, '{"Socket": "LGA1700", "Chipset": "H610", "RAM": "DDR4, 2 khe", "Kích thước": "mATX"}', 'mainboard', '{"socket": "LGA1700", "ram_type": "DDR4", "form_factor": "mATX", "ram_slots": 2, "m2_slots": 1}' FROM `categories` c WHERE c.name = 'Mainboard - Bo mạch chủ' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'MSI PRO H610M-E DDR4') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'ASUS PRIME B760M-A WIFI D4', 'Linh kiện mẫu cho Build PC (Mainboard - Bo mạch chủ).', 3200000, 10, c.id, NULL, '{"Socket": "LGA1700", "Chipset": "B760", "RAM": "DDR4, 4 khe", "Kích thước": "mATX", "Wi-Fi": "Có"}', 'mainboard', '{"socket": "LGA1700", "ram_type": "DDR4", "form_factor": "mATX", "ram_slots": 4, "m2_slots": 2}' FROM `categories` c WHERE c.name = 'Mainboard - Bo mạch chủ' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'ASUS PRIME B760M-A WIFI D4') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'MSI B760 GAMING PLUS WIFI DDR5', 'Linh kiện mẫu cho Build PC (Mainboard - Bo mạch chủ).', 4000000, 10, c.id, NULL, '{"Socket": "LGA1700", "Chipset": "B760", "RAM": "DDR5, 4 khe", "Kích thước": "ATX", "Wi-Fi": "Có"}', 'mainboard', '{"socket": "LGA1700", "ram_type": "DDR5", "form_factor": "ATX", "ram_slots": 4, "m2_slots": 2}' FROM `categories` c WHERE c.name = 'Mainboard - Bo mạch chủ' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'MSI B760 GAMING PLUS WIFI DDR5') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'MSI B550M PRO-VDH WIFI', 'Linh kiện mẫu cho Build PC (Mainboard - Bo mạch chủ).', 2600000, 10, c.id, NULL, '{"Socket": "AM4", "Chipset": "B550", "RAM": "DDR4, 4 khe", "Kích thước": "mATX", "Wi-Fi": "Có"}', 'mainboard', '{"socket": "AM4", "ram_type": "DDR4", "form_factor": "mATX", "ram_slots": 4, "m2_slots": 2}' FROM `categories` c WHERE c.name = 'Mainboard - Bo mạch chủ' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'MSI B550M PRO-VDH WIFI') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Gigabyte B650M GAMING X AX', 'Linh kiện mẫu cho Build PC (Mainboard - Bo mạch chủ).', 4200000, 10, c.id, NULL, '{"Socket": "AM5", "Chipset": "B650", "RAM": "DDR5, 4 khe", "Kích thước": "mATX", "Wi-Fi": "Có"}', 'mainboard', '{"socket": "AM5", "ram_type": "DDR5", "form_factor": "mATX", "ram_slots": 4, "m2_slots": 2}' FROM `categories` c WHERE c.name = 'Mainboard - Bo mạch chủ' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Gigabyte B650M GAMING X AX') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'ASUS TUF GAMING B650-PLUS WIFI', 'Linh kiện mẫu cho Build PC (Mainboard - Bo mạch chủ).', 5300000, 10, c.id, NULL, '{"Socket": "AM5", "Chipset": "B650", "RAM": "DDR5, 4 khe", "Kích thước": "ATX", "Wi-Fi": "Có"}', 'mainboard', '{"socket": "AM5", "ram_type": "DDR5", "form_factor": "ATX", "ram_slots": 4, "m2_slots": 3}' FROM `categories` c WHERE c.name = 'Mainboard - Bo mạch chủ' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'ASUS TUF GAMING B650-PLUS WIFI') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Kingston FURY Beast 16GB (2x8GB) DDR4 3200MHz', 'Linh kiện mẫu cho Build PC (RAM).', 900000, 10, c.id, NULL, '{"Loại": "DDR4", "Dung lượng": "16GB (2x8GB)", "Bus": "3200MHz"}', 'ram', '{"ram_type": "DDR4", "capacity_gb": 16, "modules": 2}' FROM `categories` c WHERE c.name = 'RAM' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Kingston FURY Beast 16GB (2x8GB) DDR4 3200MHz') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Corsair Vengeance LPX 32GB (2x16GB) DDR4 3200MHz', 'Linh kiện mẫu cho Build PC (RAM).', 1700000, 10, c.id, NULL, '{"Loại": "DDR4", "Dung lượng": "32GB (2x16GB)", "Bus": "3200MHz"}', 'ram', '{"ram_type": "DDR4", "capacity_gb": 32, "modules": 2}' FROM `categories` c WHERE c.name = 'RAM' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Corsair Vengeance LPX 32GB (2x16GB) DDR4 3200MHz') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Kingston FURY Beast 16GB (2x8GB) DDR5 5600MHz', 'Linh kiện mẫu cho Build PC (RAM).', 1400000, 10, c.id, NULL, '{"Loại": "DDR5", "Dung lượng": "16GB (2x8GB)", "Bus": "5600MHz"}', 'ram', '{"ram_type": "DDR5", "capacity_gb": 16, "modules": 2}' FROM `categories` c WHERE c.name = 'RAM' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Kingston FURY Beast 16GB (2x8GB) DDR5 5600MHz') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'G.Skill Trident Z5 RGB 32GB (2x16GB) DDR5 6000MHz', 'Linh kiện mẫu cho Build PC (RAM).', 2900000, 10, c.id, NULL, '{"Loại": "DDR5", "Dung lượng": "32GB (2x16GB)", "Bus": "6000MHz", "LED": "RGB"}', 'ram', '{"ram_type": "DDR5", "capacity_gb": 32, "modules": 2}' FROM `categories` c WHERE c.name = 'RAM' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'G.Skill Trident Z5 RGB 32GB (2x16GB) DDR5 6000MHz') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Corsair Vengeance 64GB (2x32GB) DDR5 6000MHz', 'Linh kiện mẫu cho Build PC (RAM).', 5600000, 10, c.id, NULL, '{"Loại": "DDR5", "Dung lượng": "64GB (2x32GB)", "Bus": "6000MHz"}', 'ram', '{"ram_type": "DDR5", "capacity_gb": 64, "modules": 2}' FROM `categories` c WHERE c.name = 'RAM' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Corsair Vengeance 64GB (2x32GB) DDR5 6000MHz') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Sapphire PULSE Radeon RX 7600 8GB', 'Linh kiện mẫu cho Build PC (Card đồ họa (VGA)).', 6900000, 10, c.id, NULL, '{"GPU": "Radeon RX 7600", "VRAM": "8GB GDDR6", "Dài": "240mm"}', 'vga', '{"tdp_w": 165, "length_mm": 240, "vram_gb": 8}' FROM `categories` c WHERE c.name = 'Card đồ họa (VGA)' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Sapphire PULSE Radeon RX 7600 8GB') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'ASUS Dual GeForce RTX 4060 8GB', 'Linh kiện mẫu cho Build PC (Card đồ họa (VGA)).', 8300000, 10, c.id, NULL, '{"GPU": "GeForce RTX 4060", "VRAM": "8GB GDDR6", "Dài": "227mm"}', 'vga', '{"tdp_w": 115, "length_mm": 227, "vram_gb": 8}' FROM `categories` c WHERE c.name = 'Card đồ họa (VGA)' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'ASUS Dual GeForce RTX 4060 8GB') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'MSI GeForce RTX 5060 VENTUS 2X 8GB', 'Linh kiện mẫu cho Build PC (Card đồ họa (VGA)).', 8900000, 10, c.id, NULL, '{"GPU": "GeForce RTX 5060", "VRAM": "8GB GDDR7", "Dài": "240mm"}', 'vga', '{"tdp_w": 145, "length_mm": 240, "vram_gb": 8}' FROM `categories` c WHERE c.name = 'Card đồ họa (VGA)' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'MSI GeForce RTX 5060 VENTUS 2X 8GB') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Gigabyte GeForce RTX 4070 SUPER WINDFORCE OC 12GB', 'Linh kiện mẫu cho Build PC (Card đồ họa (VGA)).', 16500000, 10, c.id, NULL, '{"GPU": "GeForce RTX 4070 SUPER", "VRAM": "12GB GDDR6X", "Dài": "261mm"}', 'vga', '{"tdp_w": 220, "length_mm": 261, "vram_gb": 12}' FROM `categories` c WHERE c.name = 'Card đồ họa (VGA)' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Gigabyte GeForce RTX 4070 SUPER WINDFORCE OC 12GB') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'ASUS TUF Gaming GeForce RTX 4080 SUPER 16GB', 'Linh kiện mẫu cho Build PC (Card đồ họa (VGA)).', 30500000, 10, c.id, NULL, '{"GPU": "GeForce RTX 4080 SUPER", "VRAM": "16GB GDDR6X", "Dài": "348mm"}', 'vga', '{"tdp_w": 320, "length_mm": 348, "vram_gb": 16}' FROM `categories` c WHERE c.name = 'Card đồ họa (VGA)' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'ASUS TUF Gaming GeForce RTX 4080 SUPER 16GB') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Kingston NV3 500GB NVMe PCIe 4.0', 'Linh kiện mẫu cho Build PC (Ổ cứng SSD).', 900000, 10, c.id, NULL, '{"Chuẩn": "M.2 NVMe PCIe 4.0", "Dung lượng": "500GB"}', 'storage', '{"interface": "NVMe", "capacity_gb": 500}' FROM `categories` c WHERE c.name = 'Ổ cứng SSD' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Kingston NV3 500GB NVMe PCIe 4.0') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Samsung 990 EVO Plus 1TB NVMe', 'Linh kiện mẫu cho Build PC (Ổ cứng SSD).', 2300000, 10, c.id, NULL, '{"Chuẩn": "M.2 NVMe PCIe 4.0", "Dung lượng": "1TB"}', 'storage', '{"interface": "NVMe", "capacity_gb": 1000}' FROM `categories` c WHERE c.name = 'Ổ cứng SSD' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Samsung 990 EVO Plus 1TB NVMe') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'WD Black SN850X 2TB NVMe', 'Linh kiện mẫu cho Build PC (Ổ cứng SSD).', 4200000, 10, c.id, NULL, '{"Chuẩn": "M.2 NVMe PCIe 4.0", "Dung lượng": "2TB"}', 'storage', '{"interface": "NVMe", "capacity_gb": 2000}' FROM `categories` c WHERE c.name = 'Ổ cứng SSD' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'WD Black SN850X 2TB NVMe') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Crucial BX500 480GB SATA', 'Linh kiện mẫu cho Build PC (Ổ cứng SSD).', 800000, 10, c.id, NULL, '{"Chuẩn": "SATA III 2.5\\"", "Dung lượng": "480GB"}', 'storage', '{"interface": "SATA", "capacity_gb": 480}' FROM `categories` c WHERE c.name = 'Ổ cứng SSD' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Crucial BX500 480GB SATA') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Cooler Master MWE 550 Bronze V2', 'Linh kiện mẫu cho Build PC (Nguồn máy tính (PSU)).', 1200000, 10, c.id, NULL, '{"Công suất": "550W", "Chuẩn": "80 Plus Bronze"}', 'psu', '{"wattage_w": 550}' FROM `categories` c WHERE c.name = 'Nguồn máy tính (PSU)' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Cooler Master MWE 550 Bronze V2') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Corsair CX650 650W', 'Linh kiện mẫu cho Build PC (Nguồn máy tính (PSU)).', 1600000, 10, c.id, NULL, '{"Công suất": "650W", "Chuẩn": "80 Plus Bronze"}', 'psu', '{"wattage_w": 650}' FROM `categories` c WHERE c.name = 'Nguồn máy tính (PSU)' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Corsair CX650 650W') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'MSI MAG A750GL PCIE5 750W', 'Linh kiện mẫu cho Build PC (Nguồn máy tính (PSU)).', 2300000, 10, c.id, NULL, '{"Công suất": "750W", "Chuẩn": "80 Plus Gold"}', 'psu', '{"wattage_w": 750}' FROM `categories` c WHERE c.name = 'Nguồn máy tính (PSU)' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'MSI MAG A750GL PCIE5 750W') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Corsair RM850e 850W', 'Linh kiện mẫu cho Build PC (Nguồn máy tính (PSU)).', 3100000, 10, c.id, NULL, '{"Công suất": "850W", "Chuẩn": "80 Plus Gold"}', 'psu', '{"wattage_w": 850}' FROM `categories` c WHERE c.name = 'Nguồn máy tính (PSU)' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Corsair RM850e 850W') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Cooler Master MasterBox Q300L (mATX)', 'Linh kiện mẫu cho Build PC (Vỏ máy (Case)).', 1000000, 10, c.id, NULL, '{"Hỗ trợ main": "mATX, ITX", "VGA tối đa": "360mm"}', 'case', '{"form_factors": ["mATX", "ITX"], "max_gpu_length_mm": 360}' FROM `categories` c WHERE c.name = 'Vỏ máy (Case)' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Cooler Master MasterBox Q300L (mATX)') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Montech AIR 100 ARGB (mATX)', 'Linh kiện mẫu cho Build PC (Vỏ máy (Case)).', 1100000, 10, c.id, NULL, '{"Hỗ trợ main": "mATX, ITX", "VGA tối đa": "330mm", "Quạt kèm": "4 quạt ARGB"}', 'case', '{"form_factors": ["mATX", "ITX"], "max_gpu_length_mm": 330}' FROM `categories` c WHERE c.name = 'Vỏ máy (Case)' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Montech AIR 100 ARGB (mATX)') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'NZXT H5 Flow (ATX)', 'Linh kiện mẫu cho Build PC (Vỏ máy (Case)).', 2300000, 10, c.id, NULL, '{"Hỗ trợ main": "ATX, mATX, ITX", "VGA tối đa": "365mm"}', 'case', '{"form_factors": ["ATX", "mATX", "ITX"], "max_gpu_length_mm": 365}' FROM `categories` c WHERE c.name = 'Vỏ máy (Case)' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'NZXT H5 Flow (ATX)') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Lian Li LANCOOL 216 (ATX)', 'Linh kiện mẫu cho Build PC (Vỏ máy (Case)).', 2500000, 10, c.id, NULL, '{"Hỗ trợ main": "ATX, mATX, ITX", "VGA tối đa": "392mm"}', 'case', '{"form_factors": ["ATX", "mATX", "ITX"], "max_gpu_length_mm": 392}' FROM `categories` c WHERE c.name = 'Vỏ máy (Case)' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Lian Li LANCOOL 216 (ATX)') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Thermalright Assassin X 120 Refined SE', 'Linh kiện mẫu cho Build PC (Tản nhiệt CPU).', 400000, 10, c.id, NULL, '{"Loại": "Tản khí", "Socket": "LGA1700/1851, AM4/AM5"}', 'cooler', '{"sockets": ["LGA1700", "LGA1851", "AM4", "AM5"], "tdp_rating_w": 180}' FROM `categories` c WHERE c.name = 'Tản nhiệt CPU' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Thermalright Assassin X 120 Refined SE') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'DeepCool AK400', 'Linh kiện mẫu cho Build PC (Tản nhiệt CPU).', 650000, 10, c.id, NULL, '{"Loại": "Tản khí", "Socket": "LGA1700/1851, AM4/AM5"}', 'cooler', '{"sockets": ["LGA1700", "LGA1851", "AM4", "AM5"], "tdp_rating_w": 220}' FROM `categories` c WHERE c.name = 'Tản nhiệt CPU' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'DeepCool AK400') LIMIT 1;
INSERT INTO `products` (`name`, `description`, `price`, `stock`, `category_id`, `image_url`, `specs`, `part_type`, `build_specs`) SELECT 'Corsair iCUE H100i RGB ELITE 240mm', 'Linh kiện mẫu cho Build PC (Tản nhiệt CPU).', 3400000, 10, c.id, NULL, '{"Loại": "Tản nước AIO 240mm", "Socket": "LGA1700/1851, AM4/AM5"}', 'cooler', '{"sockets": ["LGA1700", "LGA1851", "AM4", "AM5"], "tdp_rating_w": 250}' FROM `categories` c WHERE c.name = 'Tản nhiệt CPU' AND NOT EXISTS (SELECT 1 FROM `products` WHERE `name` = 'Corsair iCUE H100i RGB ELITE 240mm') LIMIT 1;

-- Kiểm tra: số linh kiện theo loại
SELECT part_type, COUNT(*) AS so_luong FROM products WHERE part_type IS NOT NULL GROUP BY part_type;
